### PR TITLE
fix: regular chat members not being able to use commands in chat scope

### LINKED ISSUE #66: addToScope with type: 'chat' incorrectly handled.
When adding a command handler specifically for regular members in a particular chat using `.addToScope({ type: "chat", chat_id: ... }, handler)`, the internal logic incorrectly applies the same processing steps as for the `{ type: "chat_administrators", ... }` scope. This is due to a missing `break` or distinct handling for the `"chat"` case in the switch statement within the `addToScope` method. As a result, an `isAdmin` filter is erroneously applied to the handler meant for all chat members. Consequently, the handler fails to execute for non-admin users because they do not pass this unintended administrative check.

https://github.com/grammyjs/commands/blob/main/src/command.ts#L321

### PR DESCRIPTION
**Pull request by rayz1065**
Fixes #66

### CODE REVIEW

File: src/command.ts [hunk 1]
```diff
@@ -319,6 +319,13 @@ export class Command<C extends Context = Context> implements MiddlewareObj<C> {
             .use(...middlewareArray);
           break;
         case "chat":
+          if (scope.chat_id) {
+            this._composer
+              .filter(Command.hasCommand(this.names, optionsObject))
+              .filter((ctx) => ctx.chat?.id === scope.chat_id)
```
Comment (KnorpelSenf) [inline src/command.ts:325]: Is there a reason why the plugin doesn't use
```suggestion
              .filter((ctx) => ctx.chatId === scope.chat_id)
```
everywhere? Is it because the extra cases were ruled out manually? Is it because of compatibility with an old version of grammY? Is it just an oversight?

Comment (carafelix) [reply src/command.ts:325]: Just an oversight

**Review by carafelix — APPROVED** [review]
LGTM! very nice tests!
