### PR TITLE
fix: filter out regex names from .toArgs

### LINKED ISSUE #24: bug: calling .setCommands(bot) on commands containing UpperCase letters or symbols will throw
Even if RegExp commands are not meant to be used / listed in the commands menu, a more appropriate error should be shown. Noted that if an error handler is not registered, it will stop execution

In my opinion it should be ok to show regexp commands in the commands menu, even if they are not meant to be used in their string representation. It should not be a problem since their names are already being registered as strings

```ts
myCommands.command(/delete_(.*)/, 'el otro', async (c) => {
   await c.reply('papito')
})

await myCommands.setCommands(bot)
```
will throw:
```bash
error: Uncaught (in promise) GrammyError: Call to 'setMyCommands' failed! (400: Bad Request: BOT_COMMAND_INVALID)
    return new GrammyError(
           ^
    at toGrammyError (https://deno.land/x/grammy@v1.22.4/core/error.ts:43:12)
    at ApiClient.callApi (https://deno.land/x/grammy@v1.22.4/core/client.ts:328:20)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async Promise.all (index 0)
    at async Commands.setCommands (file:///media/martincito/freedom/repos/grammy/commands/src/commands.ts:197:9)
    at async file:///media/martincito/freedom/repos/grammy/testbot-deno/src/bot.ts:62:1
```

Even a regex-like-string will throw:
```ts
userCommands.command('/delete/', 'el otro', async (c) => {
   await c.reply('papito')
})
```

### PR DESCRIPTION
**Pull request by carafelix**
this will fix #24 only for regex's.
Command names containing UpperCase letters will still thrown when calling `SetMyCommand` on them.

They should at least be discouraged. I don't know if it's better to enforce right from the bat the use of lowercaseonly commands or just a mention in the docs. Because they will still register and be handled correctly, but could not be pass to `SetMyCommand`

### CODE REVIEW

File: src/commands.ts [hunk 1]
```diff
@@ -157,9 +157,9 @@ export class Commands<C extends Context> {
                     language_code: language === "default"
                         ? undefined
                         : language,
-                    commands: commands.map((command) =>
-                        command.toObject(language)
-                    ),
+                    commands: commands
+                        .filter((command) => typeof command.name === "string")
+                        .map((command) => command.toObject(language)),
```
Comment (roziscoding) [inline src/commands.ts:162]: I actually think it's better if we move this kind of thing to the actual `setCommands` method, so users can still use `toArgs` and `toSingleScopeArgs` however they want. WDYT?

**Review by roziscoding — CHANGES_REQUESTED** [review]

File: src/commands.ts (hunk 1 above)
Comment (carafelix) [reply src/commands.ts:162]: Yeah, makes more sense

Comment (carafelix) [reply src/commands.ts:162]: output looks like:
```ts
[
  {
    name: "bread",
    language: "default",
    prefix: "/",
    scopes: [ { type: "default" } ],
    description: "_"
  },
  {
    name: "pan",
    language: "es",
    prefix: "/",
    scopes: [ { type: "default" } ],
    description: "_"
  },
// etc
```

Comment (roziscoding) [reply src/commands.ts:162]: Hm... yeah, that makes sense. Thanks!
