### PR TITLE
feat: add import of commands + small fixes related to command options

### LINKED ISSUE #38: Support for Exporting and Importing Commands
It would be cool if the plugin supported exporting and importing commands. This feature would enhance the modularity and reusability of command definitions, making it easier to manage and maintain large bot projects.

Something like this:

**1. Exporting a `Command`:**

```ts
import { Command } from "@grammyjs/commands";

const startCommand = new Command("start", "Initializes bot configuration")
    .addToScope(
        { type: "all_group_chats" },
        (ctx) => ctx.reply(`Hello, members of ${ctx.chat.title}!`),
    );

export default startCommand;
```

**2. Importing a `Command`**

```ts
import { Bot } from "grammy";
import { Commands } from "@grammyjs/commands";
import startCommand from "./commands/start.js";

const bot = new Bot("<telegram token>");

const myCommands = new Commands();

myCommands.define(startCommand);

// Calls `setMyCommands`
await myCommands.setCommands(bot);

// Registers the command handlers
bot.use(myCommands);

bot.start();
```

*Here maybe the `.define` could support both single `Command` or an array of `Command` (?)

### Benefits:

- **Modularity**: Commands can be organized in separate files, making the project structure cleaner and easier to manage.
- **Reusability**: Common commands can be reused across different projects by simply importing them.
- **Maintainability**: Changes to a specific command can be made in its dedicated file, reducing the risk of conflicts and making the codebase easier to maintain.

### PR DESCRIPTION
**Pull request by carafelix**
closes #38 
 ```ts
  const sayHi = new Command("hi","say hi", (ctx) => ctx.reply("hi"))
  const sayBye = new Command("bye","say bye", (ctx) => ctx.reply("bye"), { ignoreCase: true })
  const myCmds = new CommandGroup().add(sayHi).add(sayBye)
```

**fix:** merge options instead of complete override when using the `.command` creation method.

- when passing a `options` param to the `CommandGroup.command(...)` method, the default options from the command group now merges with the specific options of that command, which ofc takes priority. Before the object was being overridden completely, ignoring the default group options.
https://github.com/grammyjs/commands/blob/0f92ae16f08a1e8e991156eebd2c2fd2823f8c11/src/command-group.ts#L141-L143

**feat:** prevent whitespace only custom prefixes.

- improve the prevention for using whitespace only custom prefixes. Before it was checking only against `prefix === ""`
https://github.com/grammyjs/commands/blob/0f92ae16f08a1e8e991156eebd2c2fd2823f8c11/src/command-group.ts#L78-L79
https://github.com/grammyjs/commands/blob/0f92ae16f08a1e8e991156eebd2c2fd2823f8c11/src/command.ts#L120

### CODE REVIEW

File: src/command.ts [hunk 1]
```diff
@@ -59,22 +46,83 @@ export class Command<C extends Context = Context> implements MiddlewareObj<C> {
   };
 
   /**
-   * Constructor for the `Command` class.
-   * Do not call this directly. Instead, use the `command` method from the `Commands` class
+   * Initialize a new command with a default handler.
+   *
+   * [!IMPORTANT] This class by its own does nothing. It needs to be imported into a commandGroup
```
Comment (roziscoding) [inline src/command.ts:51]:
```suggestion
   * [!IMPORTANT] This class by its own does nothing. It needs to be imported into a `CommandGroup`
```

File: src/command.ts [hunk 2]
```diff
@@ -59,22 +46,83 @@ export class Command<C extends Context = Context> implements MiddlewareObj<C> {
...
     name: string | RegExp,
     description: string,
-    options: Partial<CommandOptions> = {},
+    handler: MaybeArray<Middleware<CommandContext<C>>>,
+    options?: Partial<CommandOptions>,
+  );
+  /**
+   * Initialize a new command with no handlers.
+   *
+   * [!IMPORTANT] This class by its own does nothing. It needs to be imported into a commandGroup
```
Comment (roziscoding) [inline src/command.ts:76]:
```suggestion
   * [!IMPORTANT] This class by its own does nothing. It needs to be imported into a `CommandGroup`
```

**Review by roziscoding — APPROVED** [review]
