### PR TITLE
fix: handle localized default scope

### LINKED ISSUE #64: Default handler doesn't work for localized command names
# Problem

The following code should handle both `/coin` and `/moeda`, but it does not recognize `/moeda` as a command. Using `addToScope` instead of passing the handler to `.command` works as expected.

```ts
import { Bot, Context } from "https://lib.deno.dev/x/grammy@v1/mod.ts";
import {
  CommandGroup,
  CommandsFlavor,
} from "https://lib.deno.dev/x/grammy_commands@v1/mod.ts";
import { LanguageCodes } from "https://lib.deno.dev/x/grammy@v1/types.ts";

const bot = new Bot(Deno.env.get("TELEGRAM_TOKEN")!);

const myCommands = new CommandGroup();

myCommands
  .command("coin", "Show coin", (ctx) => ctx.reply("Coins!!"))
  .localize(LanguageCodes.Portuguese, "moeda", "Mostra moeda");

bot.use(myCommands);

await bot.start({ onStart: (me) => console.log(`Listening as @${me.username}`) });
```

## Bonus

Calling `addToScope` before calling `localize` like this also does not work, for the same reason:

```ts
myCommands
  .command("coin", "Show coin")
  .addToScope({ type: "default" }, (ctx) => ctx.reply("Modeas"))
  .localize(LanguageCodes.Portuguese, "moeda", "Mostra moeda");
```

# Cause

This probably happens because, when we pass a handler to `CommandGroup#command`, it passes that handler to the `Command` constructor, which [uses it](https://github.com/grammyjs/commands/blob/main/src/command.ts#L144-L146) to call `addToScope` with the default scope and the handler. The `addToScope` method then [sets a new filter](https://github.com/grammyjs/commands/blob/main/src/command.ts#L296-L342) on the internal composer instance using the known command names for that command, but since it's being called by the constructor, the user hasn't even had a chance to call `localize` and add new command names.

# Solution Proposal

I can think of a few ways to solve this, but I haven't decided which one would be best. We should discuss that before implementing anything.

1. Make `localize` create a new filter on the composer using the default handler, if a default scope handler already exists.
   - How would this play with other scopes?
2. Make the `Command#middleware` method instantiate a new composer when called and implement caching and cache invalidation logic, similar to [what `CommandGroup#middleware` does](https://github.com/grammyjs/commands/blob/main/src/command-group.ts#L335-L339), so it always has all registered names.
   - This also means users can call `addToScope` before localizing and it'll work just fine.

### PR DESCRIPTION
**Pull request by roziscoding**
Fixes #64

### CODE REVIEW

File: src/command.ts [hunk 1]
```diff
@@ -58,14 +58,19 @@ export class Command<C extends Context = Context> implements MiddlewareObj<C> {
...
   private _defaultScopeComposer = new Composer<C>();
   private _options: CommandOptions = {
     prefix: "/",
     matchOnlyAtStart: true,
     targetedCommands: "optional",
     ignoreCase: false,
   };
+  private _scopeHandlers = new Map<
+    BotCommandScope,
+    [CommandOptions, Middleware<C>[] | undefined]
```
Comment (carafelix) [inline src/command.ts:70]: Could you change this into a named type? Like: `ScopeHandlers`

File: src/command.ts [hunk 2]
```diff
@@ -518,7 +479,64 @@ export class Command<C extends Context = Context> implements MiddlewareObj<C> {
   }
 
   middleware() {
-    return new Composer(this._composer, this._defaultScopeComposer)
-      .middleware();
+    if (this._cachedComposerInvalidated) {
+      const entries = this._scopeHandlers.entries();
+
+      for (const [scope, [optionsObject, middlewareArray]] of entries) {
```
Comment (carafelix) [inline src/command.ts:485]: I would prefer this to be a private named function like `RegisterScopes(entries : ScopeHandlers)` to keep the `middleware` function more succinct

File: test/command.test.ts [hunk 3]
```diff
@@ -12,10 +12,14 @@ import {
...
   it,
   type Message,
+  spy,
   type Update,
   type User,
   type UserFromGetMe,
 } from "./deps.test.ts";
+import { Composer } from "../src/deps.deno.ts";
+import { LanguageCodes } from "../src/language-codes.ts";
+import { Filter } from "https://deno.land/x/grammy@v1.34.1/mod.ts";
```
Comment (carafelix) [inline test/command.test.ts:22]: unused import
```suggestion
- import { Filter } from "https://deno.land/x/grammy@v1.34.1/mod.ts";
```

**Review by carafelix — CHANGES_REQUESTED** [review]
Mainly small things

**Review by carafelix — CHANGES_REQUESTED** [review]
Mainly small things :3 Gj.
I can resolve the conflicts afterwards if u are busy, they are small, (almost) mostly resolved by accepting the combination of the 2 branches

File: src/command.ts (hunk 1 above)
Comment (roziscoding) [reply src/command.ts]: Done!

File: src/command.ts (hunk 2 above)
Comment (roziscoding) [reply src/command.ts]: Done :)

**Review by carafelix — APPROVED** [review]
[Nice <3](https://media1.tenor.com/m/PeJoMf_q5_QAAAAC/noice-nice.gif)
